const products = [
  {
    name: "Tomatoes",
    price: 25,
    owner: "Latif",
    qnty: 2.5,
    image: "tomatoes.jpeg",
    description: "It is foreign tomatoes from Brazil",
    id: "fc1004@25",
    isNew: true,
  },
  {
    name: "Soyabeans",
    price: 400,
    owner: "Desmond",
    qnty: 7,
    image: "soyabeans.jpeg",
    description: "Brifor first class soyabeans",
    id: "fc1024@22",
    isNew: false,
  },
  {
    name: "Tomatoes",
    price: 25,
    owner: "Latif",
    qnty: 2.5,
    image: "tomatoes.jpeg",
    description: "It is foreign tomatoes from Brazil",
    id: "fc1004@25",
    isNew: true,
  },
  {
    name: "Soyabeans",
    price: 400,
    owner: "Desmond",
    qnty: 7,
    image: "soyabeans.jpeg",
    description: "Brifor first class soyabeans",
    id: "fc1024@22",
    isNew: false,
  },
  {
    name: "Tomatoes",
    price: 25,
    owner: "Latif",
    qnty: 2.5,
    image: "tomatoes.jpeg",
    description: "It is foreign tomatoes from Brazil",
    id: "fc1004@25",
    isNew: true,
  },
  {
    name: "Soyabeans",
    price: 400,
    owner: "Desmond",
    qnty: 7,
    image: "soyabeans.jpeg",
    description: "Brifor first class soyabeans",
    id: "fc1024@22",
    isNew: false,
  },
];

module.exports = products;
